### ISSUE TITLE
Python-mystrom AttributeError:

### ISSUE THREAD

**Issue by gwaag** [home-assistant-ecosystem/python-mystrom#24]
This is the error I get running the sample code.

plug = pymystrom.MyStromPlug('192.168.0.34')
AttributeError: module 'pymystrom' has no attribute 'MyStromPlug'

What could be the problem`?
regards
tb

**Comment by fabaff** [comment]
I refactored the code a while back and it included a change of the naming (plug was replaced with switch because myStrom uses that terminology).

The [`examples`](https://github.com/home-assistant-ecosystem/python-mystrom/tree/master/examples) directory contains more up-to-date code.

Sorry for the inconvenience.
